services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # web
      - 8266:8266 # peers
    environment:
      - TZ=${TZ:-Australia/Sydney}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - serverIP=tdarr
    volumes:
      - ./tdarr/configs:/app/configs
      - ./tdarr/server:/app/server
      - /mnt/gaza:/mnt/gaza
    networks:
      - tdarr-net
      - proxy-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8265 || exit 1"]
      interval: 60s
      start_period: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Australia/Sydney}
      - PUID=${PGID:-1000}
      - PGID=${PGID:-1000}
      - nodeID=${NODE_ID}
      - serverIP=tdarr
      - serverPort=8266
    volumes:
      - ./tdarr/configs:/app/configs
      - /mnt/gaza:/mnt/gaza
    networks:
      - tdarr-net
      - proxy-net
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep Tdarr_Node | grep -v grep || exit 1"]
      interval: 60s
      start_period: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G

networks:
  tdarr-net:
    driver: bridge
  proxy-net:
    external: true
