services:
  dynacat:
    image: panonim/dynacat:latest
    container_name: dynacat
    restart: unless-stopped
    volumes:
      - ./dynacat/config:/app/config
      - ./dynacat/assets:/assets
      - /mnt/gaza:/mnt/gaza
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    networks:
      - proxy-net
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8081 || exit 1"]
      interval: 60s
      start_period: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  proxy-net:
    external: true
