services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PGID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Australia/Sydney}
    volumes:
      - ./heimdall/config:/config
    ports:
      - 8081:80
    networks:
      - proxy-net
    healthcheck:
      test: "curl --fail http://localhost"
      interval: 60s
      timeout: 10s
      start_period: 10s

networks:
  proxy-net:
    external: true
