services:
  seerr:
    image: seerr/seerr:latest
    container_name: seerr
    restart: unless-stopped
    user: 1000:1000
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Australia/Sydney}
      - LOG_LEVEL=debug
    volumes:
      - /opt/stacks/view/seerr/config:/app/config
      - /mnt/gaza/media:/data/media_gaza
      - /mnt/galilee/media:/data/media_galilee
    ports:
      - 5055:5055
    networks:
      - media-net
      - proxy-net
    healthcheck:
      test: wget http://localhost:5055/api/v1/status -qO /dev/null || exit 1
      interval: 60s
      timeout: 20s
      start_period: 30s

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Australia/Sydney}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL}
    volumes:
      - ./jellyfin/config:/config
      - /mnt/gaza/media:/data/media_gaza
      - /mnt/galilee/media:/data/media_galilee
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    ulimits:
      nofile:
        soft: 8192
        hard: 65536
    networks:
      - media-net
      - proxy-net
    healthcheck:
      test: curl --fail http://localhost:8096 || exit 1
      interval: 60s
      timeout: 20s
      start_period: 30s

  qui:
    image: ghcr.io/hotio/qui
    container_name: qui
    restart: unless-stopped
    ports:
      - 7476:7476
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Australia/Sydney}
      - UMASK=002
      - WEBUI_PORTS=7476/tcp
    volumes:
      - ./qui/config:/config
    networks:
      - media-net
      - proxy-net
    healthcheck:
      test: curl --fail http://localhost:7476 || exit 1
      interval: 60s
      timeout: 10s
      start_period: 10s

networks:
  media-net:
    driver: bridge
  proxy-net:
    external: true
